from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
# Visual system: dark-first, colorful financial semantics.
s=s.replace('<meta name="theme-color" content="#315efb">','<meta name="theme-color" content="#07111f">')
s=s.replace(':root{--bg:#f4f7fb;--card:#fff;--text:#101828;--muted:#748198;--line:#e6ebf2;--blue:#315efb;--green:#10b981;--red:#f04464;--purple:#8b5cf6;--orange:#f59e0b;--shadow:0 8px 26px #23395d12}body.dark{--bg:#07111f;--card:#111c2e;--text:#f8fafc;--muted:#9aa8bd;--line:#20314a}',':root{--bg:#07111f;--card:#111c2e;--text:#f8fafc;--muted:#9aa8bd;--line:#20314a;--blue:#2f80ed;--green:#18d3a7;--red:#ff5d73;--purple:#a78bfa;--orange:#ff8a65;--yellow:#fbbf24;--cyan:#22d3ee;--shadow:0 12px 30px #00000024}body.light{--bg:#f4f7fb;--card:#fff;--text:#101828;--muted:#748198;--line:#e6ebf2}')
s=s.replace('.hero{padding:18px;border-radius:25px;color:#fff;background:linear-gradient(135deg,#7c3aed,#315efb 52%,#06b6d4);box-shadow:var(--shadow)}','.hero{padding:20px;border-radius:27px;color:#fff;background:linear-gradient(145deg,#0c3b45,#0b2238 58%,#111c2e);border:1px solid #18d3a755;box-shadow:var(--shadow)}')
s=s.replace('.g1{background:linear-gradient(135deg,#10b981,#06b6d4)}.g2{background:linear-gradient(135deg,#fb4667,#ec4899)}.g3{background:linear-gradient(135deg,#3b82f6,#1d4ed8)}.g4{background:linear-gradient(135deg,#7c3aed,#c026d3)}','.g1{background:linear-gradient(135deg,#0b806b,#18d3a7)}.g2{background:linear-gradient(135deg,#d43f5d,#ff6f61)}.g3{background:linear-gradient(135deg,#2457c5,#2f80ed)}.g4{background:linear-gradient(135deg,#7048d7,#a855f7)}')
s=s.replace('.feature.hot{background:linear-gradient(135deg,#111c4d,#315efb);color:#fff}', '.feature.hot{background:linear-gradient(135deg,#0d3b46,#0f766e);color:#fff;border-color:#18d3a755}')
s=s.replace('.nav.active{color:var(--blue)}','.nav.active{color:var(--green);background:#18d3a715;border-radius:16px;padding:6px 3px}')
s=s.replace('.plus{width:49px;height:49px;border-radius:16px;background:linear-gradient(135deg,#3b82f6,#315efb);','.plus{width:49px;height:49px;border-radius:16px;background:linear-gradient(135deg,#18d3a7,#2f80ed);')
# Make beta status less intrusive.
s=s.replace('<div class="head"><h1>עוד</h1><small class="muted">BETA</small></div>','<div class="head"><h1>עוד</h1></div>')
# Do not advertise integrations that are not implemented.
s=s.replace('<button class="feature" data-go="bank"><span>🏦</span><b>Open Banking</b><small>CSV וחיבור עתידי</small></button><button class="feature" data-go="email"><span>✉️</span><b>מייל</b><small>Gmail, Outlook ועוד</small></button>','<button class="feature" type="button" disabled><span>🏦</span><b>חיבור בנק</b><small>בקרוב · לאחר חיבור מאובטח</small></button><button class="feature" type="button" disabled><span>✉️</span><b>ייבוא ממייל</b><small>בקרוב · OAuth מאובטח</small></button>')
# Persistent model improvements while keeping backwards compatibility.
s=s.replace("travel:{}},JSON.parse(localStorage.getItem(KEY)||'{}'));['transactions','categories','reminders','goals','debts','documents'].forEach", "travel:{},recurringTransactions:[]},JSON.parse(localStorage.getItem(KEY)||'{}'));['transactions','categories','reminders','goals','debts','documents','recurringTransactions'].forEach")
s=s.replace("let editingId=null,txView='all';const fmt=n=>new Intl.NumberFormat(st.locale||'he-IL',{style:'currency',currency:st.currency||'ILS',maximumFractionDigits:0}).format(+n||0);", "let editingId=null,txView='all';const toMinor=n=>Math.round((+n||0)*100),fromMinor=n=>(+n||0)/100;st.transactions.forEach(t=>{if(!Number.isInteger(t.amountMinor))t.amountMinor=toMinor(t.amount);t.amount=fromMinor(t.amountMinor)});if(st.salary>0&&!st.recurringTransactions.some(r=>r.kind==='salary')){st.recurringTransactions.push({id:'salary-'+Date.now(),kind:'salary',type:'income',category:'משכורת',amountMinor:toMinor(st.salary),day:1,start:new Date().toISOString().slice(0,7),active:true});st.salary=0;localStorage.setItem(KEY,JSON.stringify(st))}const fmt=n=>new Intl.NumberFormat(st.locale||'he-IL',{style:'currency',currency:st.currency||'ILS',minimumFractionDigits:0,maximumFractionDigits:2}).format(+n||0);function ensureRecurring(m){(st.recurringTransactions||[]).forEach(r=>{if(!r.active||r.start>m||(r.end&&r.end<m))return;let id='rec:'+r.id+':'+m;if(st.transactions.some(t=>t.id===id))return;let day=Math.min(+r.day||1,new Date(+m.slice(0,4),+m.slice(5,7),0).getDate()),amount=fromMinor(r.amountMinor);st.transactions.push({id,type:r.type||'income',category:r.category||'הכנסה קבועה',amount,amountMinor:r.amountMinor,date:m+'-'+String(day).padStart(2,'0'),source:'recurring',recurringId:r.id})});localStorage.setItem(KEY,JSON.stringify(st))}")
old="function calc(m=new Date().toISOString().slice(0,7)){let a=st.transactions.filter(x=>(x.date||'').slice(0,7)===m),inc=a.filter(x=>x.type==='income').reduce((s,x)=>s+(+x.amount||0),0)+(m===new Date().toISOString().slice(0,7)?+st.salary||0:0),exp=a.filter(x=>x.type==='expense').reduce((s,x)=>s+(+x.amount||0),0),saved=a.filter(x=>x.type==='saving').reduce((s,x)=>s+(+x.amount||0),0);return{a,inc,exp,saved,left:inc-exp-saved}}"
new="function calc(m=new Date().toISOString().slice(0,7)){ensureRecurring(m);let a=st.transactions.filter(x=>(x.date||'').slice(0,7)===m),sum=t=>a.filter(x=>x.type===t).reduce((n,x)=>n+(Number.isInteger(x.amountMinor)?x.amountMinor:toMinor(x.amount)),0),inc=fromMinor(sum('income')),exp=fromMinor(sum('expense')),saved=fromMinor(sum('saving'));return{a,inc,exp,saved,left:inc-exp-saved}}"
s=s.replace(old,new)
# Store new transactions in minor units.
s=s.replace("let tx={id:editingId||Date.now()+Math.random(),type,amount,category:cat,date:", "let tx={id:editingId||Date.now()+Math.random(),type,amount,amountMinor:toMinor(amount),category:cat,date:")
# Onboarding salary becomes a recurring transaction rather than a magic current-month number.
s=s.replace("$('onFinish').onclick=()=>{st.salary=mode==='budget'?0:+$('onSalary').value||0;st.budget=mode==='salary'?0:+$('onBudget').value||0;st.savingGoal=+$('onSaving').value||0;st.onboarded=true;save();render()};", "$('onFinish').onclick=()=>{let sal=mode==='budget'?0:+$('onSalary').value||0;st.salary=0;st.budget=mode==='salary'?0:+$('onBudget').value||0;st.savingGoal=+$('onSaving').value||0;if(sal>0)st.recurringTransactions.push({id:'salary-'+Date.now(),kind:'salary',type:'income',category:'משכורת',amountMinor:toMinor(sal),day:1,start:new Date().toISOString().slice(0,7),active:true});st.onboarded=true;save();render()};")
# Default dark mode for new users, preserve explicit light choice.
s=s.replace("theme:'light'", "theme:'dark'")
s=s.replace("document.body.classList.toggle('dark',st.theme==='dark');", "document.body.classList.toggle('light',st.theme==='light');")
# Better error UX: toast for storage failure instead of raw alert.
s=s.replace("alert('לא ניתן לשמור כרגע. בדוק שיש מקום פנוי בדפדפן ונסה שוב.');return false", "toast('לא ניתן לשמור. מומלץ להוריד גיבוי ולנסות שוב.');return false")
# Remove fake provider click handlers from active UI.
s=s.replace("document.querySelectorAll('[data-mail]').forEach(b=>b.onclick=()=>alert(`חיבור ${b.dataset.mail} יתבצע באמצעות OAuth רשמי.`));", "document.querySelectorAll('[data-mail]').forEach(b=>{b.disabled=true;b.textContent='בקרוב'});")
p.write_text(s,encoding='utf-8')
